# Generated by Django 4.1.5 on 2023-01-13 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaringadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpassword',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 2, 5, 11, 691225)),
        ),
    ]
